name: Generate Weekly QR Code

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_qr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Or your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run QR code script
        run: |
          python app.py

      - name: Upload QR code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: qr-code
          path: qr-*.png
