name: Generate QR Code from URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Google Doc URL to encode"
        required: true
        type: string

jobs:
  generate_qr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Create QR code from input URL
        run: |
          echo "Generating QR for: ${{ github.event.inputs.url }}"
          python your_script.py "${{ github.event.inputs.url }}"

      - name: Upload QR code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: qr-code
          path: qr-*.png
